import { styled } from "../../stitches.config";
import React, { ReactElement } from "react";
import Head from "next/head";

const StyledMain = styled("main", {
  display: "flex",
});

const PageSection = styled("section", {
  width: "100%",
});

export default function Layout({ children }: { children: ReactElement }) {
  return (
    <>
      <Head>
        <title>Tie-dye</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMain>
        <PageSection>{children}</PageSection>
      </StyledMain>
    </>
  );
}
